language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.1.1
    - android-22
    - android-27
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
